// SPDX-License-Identifier: AGPL-3.0-only
import {beforeEach,expect,it,vi} from "vitest";
import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {i18n} from "../../../i18n";
import ActivityDiscoveries from "./ActivityDiscoveries";
const mocks=vi.hoisted(()=>({distill:vi.fn(),refinements:vi.fn(),accept:vi.fn(),reject:vi.fn()}));
vi.mock("../../../lib/tauri",()=>({distillReview:mocks.distill,listRefinements:mocks.refinements,acceptRefinement:mocks.accept,rejectRefinement:mocks.reject}));
const result={pages_created:0,scoped:false,created_ids:[],pending:[{source_ids:['a','b'],contents:['First source','Second source'],space:'Travel',estimated_tokens:20}],stale_pages:[],stale_truncated:false,orphan_topics:[{label:'Packing',count:2}]};
function mount(){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={client}><ActivityDiscoveries/></QueryClientProvider>);}
beforeEach(async()=>{vi.clearAllMocks();await i18n.changeLanguage('en');mocks.distill.mockResolvedValue(result);mocks.refinements.mockResolvedValue({proposals:[{id:'cross-1',action:'cross_space_discovery',source_ids:['a','b'],payload:{action:'cross_space_discovery',spaces:['Travel','Reading'],memory_count:2},confidence:0.8,created_at:null}]});});
it('loads and shows suggestions directly without approval or automatic dismissal',async()=>{mount();const region=await screen.findByRole('region',{name:'Suggestions'});expect(region.querySelector(':scope > details')).toBeNull();expect(screen.getByText('Possible pages and related material, drawn from your library.')).toBeVisible();expect(await screen.findByRole('heading',{name:'Suggested pages',level:3})).toBeVisible();expect(await screen.findByRole('heading',{name:'Related memories',level:3})).toBeVisible();expect(await screen.findByRole('heading',{name:'Topics to explore',level:3})).toBeVisible();expect(await screen.findByText('Travel',{exact:true})).toBeVisible();expect(screen.getByText('Memories across spaces')).toBeVisible();expect(screen.getByText('2 memories across: Travel · Reading')).toBeVisible();expect(screen.queryByText(/Confidence/)).toBeNull();expect(screen.getByText('Packing')).toBeVisible();expect(screen.getByText(/Not generated yet/)).toBeVisible();expect(screen.queryByText(/These sources could form a note/)).toBeNull();await userEvent.click(screen.getByText('Source memories',{exact:true}));expect(screen.getByText('First source')).toBeVisible();expect(screen.queryByRole('button',{name:/accept|approve|skip/i})).toBeNull();expect(screen.getByRole('button',{name:'Dismiss'})).toBeVisible();expect(mocks.accept).not.toHaveBeenCalled();expect(mocks.reject).not.toHaveBeenCalled();});
it('keeps actionable and example records out of informational findings',async()=>{mocks.refinements.mockResolvedValue({proposals:[{id:'example:one',action:'cross_space_discovery',source_ids:[],payload:null,confidence:0,created_at:null},{id:'contradiction',action:'detect_contradiction',source_ids:['a','b'],payload:{action:'detect_contradiction'},confidence:0.8,created_at:null}]});mocks.distill.mockResolvedValue({...result,pending:[],orphan_topics:[]});mount();expect(await screen.findByText('No suggestions found.')).toBeVisible();});
it('retains successful partial results, reports failure, and retries the read',async()=>{mocks.refinements.mockRejectedValueOnce(new Error('offline')).mockResolvedValue({proposals:[]});mount();expect(await screen.findByRole('alert')).toHaveTextContent('Could not load all suggestions');expect(screen.getByText('Travel',{exact:true})).toBeVisible();expect(screen.queryByText('No suggestions found.')).toBeNull();await userEvent.click(screen.getByRole('button',{name:'Reload suggestions'}));await waitFor(()=>expect(screen.queryByRole('alert')).toBeNull());expect(mocks.refinements).toHaveBeenCalledTimes(2);});
it('reports capped lists instead of claiming an empty complete result',async()=>{mocks.refinements.mockResolvedValue({proposals:Array.from({length:50},(_,i)=>({id:`example:${i}`,action:'cross_space_discovery',source_ids:[],payload:null,confidence:0,created_at:null}))});mocks.distill.mockResolvedValue({...result,pending:[],orphan_topics:[]});mount();expect(await screen.findByText('Only part of the suggestions list is shown.')).toBeVisible();expect(screen.queryByText('No suggestions found.')).toBeNull();});
it('dismisses unsupported proposals through the daemon and reports failures without hiding them',async()=>{mocks.reject.mockRejectedValueOnce(new Error('Could not dismiss this suggestion')).mockResolvedValue({id:'cross-1'});const {container}=mount();const dismiss=await screen.findByRole('button',{name:'Dismiss'});await userEvent.click(dismiss);expect(await screen.findByRole('alert')).toHaveTextContent('Could not dismiss this suggestion');expect(screen.getByText('Memories across spaces')).toBeVisible();expect(mocks.reject).toHaveBeenCalledWith('cross-1');mocks.reject.mockResolvedValue({id:'cross-1'});await userEvent.click(screen.getByRole('button',{name:'Dismiss'}));await waitFor(()=>expect(mocks.refinements).toHaveBeenCalledTimes(2));expect(mocks.accept).not.toHaveBeenCalled();expect(container.querySelector('[role="alert"]')).toBeNull();});
it('honors existing candidate and topic hides and lets Activity restore them',async()=>{localStorage.setItem('wenlan.review.hidden.v1',JSON.stringify([{key:'topic:Packing',label:'Packing',kind:'topic',at:Date.now()},{key:'candidate:travel',label:'Travel',kind:'page_candidate',at:Date.now()}]));mount();await waitFor(()=>expect(screen.queryByRole('heading',{name:'Packing'})).toBeNull());expect(screen.queryByRole('heading',{name:'Travel'})).toBeNull();await userEvent.click(screen.getByText('Hidden',{exact:true}));const restores=screen.getAllByRole('button',{name:'Restore'});await userEvent.click(restores[0]);await waitFor(()=>expect(screen.getByRole('heading',{name:'Packing'})).toBeVisible());await userEvent.click(screen.getByText('Hidden',{exact:true}));await userEvent.click(screen.getByText('Hidden',{exact:true}));await userEvent.click(screen.getByRole('button',{name:'Restore'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'Travel'})).toBeVisible());});
