// SPDX-License-Identifier: AGPL-3.0-only
// Copy for the user-triggered, deterministic knowledge check surface.

export const enKnowledgeCheck = {
  title: "Knowledge check",
  back: "Back to Activity",
  check: "Check knowledge",
  checkAgain: "Check again",
  retryCheck: "Retry check",
  repairItems_one: "Repair {{count}} item",
  repairItems_other: "Repair {{count}} items",
  repairItem: "Repair this item",
  recover: "Check repair status",
  checking: "Checking your knowledge…",
  repairing: "Applying approved repairs…",
  recovering: "Checking the repair status…",
  checkedSummary_one: "{{count}} item needs attention. {{automatic}} can be repaired automatically.",
  checkedSummary_other: "{{count}} items need attention. {{automatic}} can be repaired automatically.",
  noIssues: "No issues were found in the checked knowledge.",
  noFurtherRepairs: "No further automatic repairs are available for this check.",
  incomplete: "Only part of the knowledge could be checked. Review the details before relying on this result.",
  planIncomplete: "Some findings could not be fully prepared for repair.",
  checkFailed: "The knowledge check could not finish.",
  pausedSafe: "Run a fresh check before continuing with the remaining items.",
  recoverRequired: "A repair may have been applied. Check its status before starting another repair.",
  repairProgress: "{{verified}} of {{total}} items verified; {{remaining}} remain.",
  allVerified: "All selected repairs were verified.",
  restoredSummary_one: "Saved progress: {{count}} item needs attention.",
  restoredSummary_other: "Saved progress: {{count}} items need attention.",
  noPlan: "Check links and the structure of your knowledge.",
  scope: "All spaces",
  status: {
    automatic: "Automatic repair",
    review: "Needs your review",
    blocked: "Needs attention",
    system: "Needs attention",
    manual: "Manual step",
    verified: "Verified",
    applying: "Applying",
    unverified: "Applied, not yet verified",
    failed: "Could not repair",
    pending: "Not started",
  },
  pagination: "Knowledge check pages",
  previousPage: "Previous",
  nextPage: "Next",
  pageCount: "Page {{current}} of {{total}}",
  issue: {
    memoryState: "Memory state needs repair",
    tagIntegrity: "Tag association needs repair",
    supersession: "Memory relationship needs repair",
    enrichment: "Memory processing needs attention",
    memoryEntity: "Memory and topic link needs attention",
    duplicateTitles: "Pages share the same title",
    orphanLabels: "A Page link needs reconnecting",
    projectionVersion: "A Page file needs refreshing",
    projectionIdentity: "A Page file needs alignment",
    sourcePage: "A source Page needs attention",
    semantic: "Knowledge needs your review",
    unknown: "Knowledge item needs attention",
  },
  detail: "Issue details",
  affected: "Affected item",
  unavailable: "The affected item is unavailable.",
  titleUnavailable: "Could not load the affected item name.",
  change: "Proposed change",
  before: "Current",
  after: "After repair",
  openOriginal: "Open original",
  reviewItem: "Review item",
  unsupportedReady: "This change needs a manual step. Open the affected item to continue.",
  reviewHint: "This finding needs a decision before it can be resolved.",
  blockedHint: "This item is blocked. Follow the next step below, then run the check again.",
  systemHint: "This item needs an action in Wenlan before you can continue.",
  systemNext: {
    schema: "Update the database, then check again.",
    searchIndex: "Rebuild the search index, then check again.",
    update: "Update Wenlan, then check again.",
    restart: "Restart Wenlan, then check again.",
    routeScope: "Check that the route uses the intended space.",
    unknown: "Open the details to see what needs attention.",
  },
  nextStep: "Next step",
  orphanLinkNextStep: "Create the missing page or correct this link in the original page.",
  statusDetails: "Repair status details",
  errorDetails: "Technical details",
  page: "Page",
  memory: "Memory",
  entity: "Topic",
  other: "Knowledge item",
  memoryType: {
    identity: "Identity",
    preference: "Preference",
    decision: "Decision",
    lesson: "Lesson",
    gotcha: "Caution",
    fact: "Fact",
    unset: "Not set",
    unknown: "Other type",
  },
  mutation: {
    reclassify: "Memory type",
    bindLink: "Page link",
    linked: "Linked to a different Page",
    notLinked: "“{{label}}” is not linked",
    targetLoading: "Loading linked Page…",
    sourceLabel: "Source label",
    emptySourceLabel: "Empty source label",
    noSourceLabel: "No source label",
    memoryRelationship: "Memory relationship",
    selfReference: "Points to itself",
    selfReferenceRemoved: "Self-reference removed",
    memoryTopicLink: "Memory and topic link",
    brokenMemoryTopicLink: "Broken memory and topic link",
    brokenMemoryTopicLinkRemoved: "Broken link removed; memory and topic remain",
  },
};

export const hantKnowledgeCheck = {
  title: "知識檢查",
  back: "返回活動",
  check: "檢查知識",
  checkAgain: "重新檢查",
  retryCheck: "重新檢查",
  repairItems_one: "一鍵修復 {{count}} 項",
  repairItems_other: "一鍵修復 {{count}} 項",
  repairItem: "修復此項目",
  recover: "確認修復狀態",
  checking: "正在檢查知識…",
  repairing: "正在套用已確認的修復…",
  recovering: "正在確認修復狀態…",
  checkedSummary_one: "有 {{count}} 個項目需要處理，其中 {{automatic}} 個可自動修復。",
  checkedSummary_other: "有 {{count}} 個項目需要處理，其中 {{automatic}} 個可自動修復。",
  noIssues: "檢查範圍內沒有發現問題。",
  noFurtherRepairs: "這次檢查已沒有可自動修復的項目。",
  incomplete: "只能完成部分知識檢查。請先查看詳細資訊，再判斷結果。",
  planIncomplete: "部分發現尚未完成修復準備。",
  checkFailed: "知識檢查無法完成。",
  pausedSafe: "請重新檢查，再繼續處理剩餘項目。",
  recoverRequired: "修復可能已經套用。請先確認狀態，再開始其他修復。",
  repairProgress: "{{total}} 個項目中有 {{verified}} 個已確認，還有 {{remaining}} 個待處理。",
  allVerified: "所選修復都已確認。",
  restoredSummary_one: "已還原進度：還有 {{count}} 個項目需要處理。",
  restoredSummary_other: "已還原進度：還有 {{count}} 個項目需要處理。",
  noPlan: "檢查筆記連結與知識結構。",
  scope: "所有空間",
  status: {
    automatic: "可自動修復",
    review: "需要你確認",
    blocked: "需要處理",
    system: "需要處理",
    manual: "手動處理",
    verified: "已確認",
    applying: "修復中",
    unverified: "已套用，尚未確認",
    failed: "修復失敗",
    pending: "尚未開始",
  },
  pagination: "知識檢查頁面",
  previousPage: "上一頁",
  nextPage: "下一頁",
  pageCount: "第 {{current}} 頁，共 {{total}} 頁",
  issue: {
    memoryState: "記憶狀態需要修復",
    tagIntegrity: "標籤關聯需要修復",
    supersession: "記憶關係需要修復",
    enrichment: "記憶處理需要留意",
    memoryEntity: "記憶與主題的連結需要留意",
    duplicateTitles: "多篇筆記使用相同標題",
    orphanLabels: "筆記連結需要重新連接",
    projectionVersion: "筆記檔案需要更新",
    projectionIdentity: "筆記檔案需要同步",
    sourcePage: "來源筆記需要留意",
    semantic: "知識項目需要你確認",
    unknown: "知識項目需要處理",
  },
  detail: "問題詳細資訊",
  affected: "受影響項目",
  unavailable: "無法取得受影響項目。",
  titleUnavailable: "無法載入受影響項目的名稱。",
  change: "預計變更",
  before: "目前內容",
  after: "修復後",
  openOriginal: "開啟原項目",
  reviewItem: "檢視項目",
  unsupportedReady: "此變更需要手動處理。請開啟受影響項目以繼續。",
  reviewHint: "此發現需要先做出決定才能處理。",
  blockedHint: "此項目目前無法處理。請先完成下方步驟，再重新檢查。",
  systemHint: "此項目需要先在 Wenlan 中處理，才能繼續。",
  systemNext: {
    schema: "更新資料庫後再重新檢查。",
    searchIndex: "重建搜尋索引後再重新檢查。",
    update: "更新 Wenlan 後再重新檢查。",
    restart: "重新啟動 Wenlan 後再重新檢查。",
    routeScope: "確認此連結使用的空間正確，再重新檢查。",
    unknown: "開啟詳細資訊查看需要處理的內容。",
  },
  nextStep: "下一步",
  orphanLinkNextStep: "建立缺少的筆記，或在原筆記中修正此連結。",
  statusDetails: "修復狀態詳細資訊",
  errorDetails: "技術詳細資訊",
  page: "筆記",
  memory: "記憶",
  entity: "主題",
  other: "知識項目",
  memoryType: {
    identity: "身分",
    preference: "偏好",
    decision: "決定",
    lesson: "經驗",
    gotcha: "注意事項",
    fact: "事實",
    unset: "未設定",
    unknown: "其他類型",
  },
  mutation: { reclassify: "記憶類型", bindLink: "筆記連結", linked: "已連結至其他筆記", notLinked: "「{{label}}」尚未連結", targetLoading: "正在載入連結筆記…", sourceLabel: "來源標籤", emptySourceLabel: "來源標籤為空", noSourceLabel: "沒有來源標籤", memoryRelationship: "記憶關係", selfReference: "指向自身", selfReferenceRemoved: "已移除自我參照", memoryTopicLink: "記憶與主題的連結", brokenMemoryTopicLink: "記憶與主題的連結已失效", brokenMemoryTopicLinkRemoved: "已移除失效連結；記憶與主題都會保留" },
};

export const hansKnowledgeCheck = {
  title: "知识检查",
  back: "返回活动",
  check: "检查知识",
  checkAgain: "重新检查",
  retryCheck: "重新检查",
  repairItems_one: "一键修复 {{count}} 项",
  repairItems_other: "一键修复 {{count}} 项",
  repairItem: "修复此项目",
  recover: "确认修复状态",
  checking: "正在检查知识…",
  repairing: "正在应用已确认的修复…",
  recovering: "正在确认修复状态…",
  checkedSummary_one: "有 {{count}} 个项目需要处理，其中 {{automatic}} 个可自动修复。",
  checkedSummary_other: "有 {{count}} 个项目需要处理，其中 {{automatic}} 个可自动修复。",
  noIssues: "检查范围内没有发现问题。",
  noFurtherRepairs: "本次检查已没有可自动修复的项目。",
  incomplete: "只能完成部分知识检查。请先查看详细信息，再判断结果。",
  planIncomplete: "部分发现尚未完成修复准备。",
  checkFailed: "知识检查无法完成。",
  pausedSafe: "请重新检查，再继续处理剩余项目。",
  recoverRequired: "修复可能已经应用。请先确认状态，再开始其他修复。",
  repairProgress: "{{total}} 个项目中有 {{verified}} 个已确认，还有 {{remaining}} 个待处理。",
  allVerified: "所选修复都已确认。",
  restoredSummary_one: "已恢复进度：还有 {{count}} 个项目需要处理。",
  restoredSummary_other: "已恢复进度：还有 {{count}} 个项目需要处理。",
  noPlan: "检查笔记链接与知识结构。",
  scope: "所有空间",
  status: {
    automatic: "可自动修复",
    review: "需要你确认",
    blocked: "需要处理",
    system: "需要处理",
    manual: "手动处理",
    verified: "已确认",
    applying: "修复中",
    unverified: "已应用，尚未确认",
    failed: "修复失败",
    pending: "尚未开始",
  },
  pagination: "知识检查页面",
  previousPage: "上一页",
  nextPage: "下一页",
  pageCount: "第 {{current}} 页，共 {{total}} 页",
  issue: {
    memoryState: "记忆状态需要修复",
    tagIntegrity: "标签关联需要修复",
    supersession: "记忆关系需要修复",
    enrichment: "记忆处理需要留意",
    memoryEntity: "记忆与主题的关联需要留意",
    duplicateTitles: "多篇笔记使用相同标题",
    orphanLabels: "笔记链接需要重新连接",
    projectionVersion: "笔记文件需要更新",
    projectionIdentity: "笔记文件需要同步",
    sourcePage: "来源笔记需要留意",
    semantic: "知识项目需要你确认",
    unknown: "知识项目需要处理",
  },
  detail: "问题详细信息",
  affected: "受影响项目",
  unavailable: "无法取得受影响项目。",
  titleUnavailable: "无法加载受影响项目的名称。",
  change: "预计变更",
  before: "当前内容",
  after: "修复后",
  openOriginal: "打开原项目",
  reviewItem: "查看项目",
  unsupportedReady: "此变更需要手动处理。请打开受影响项目以继续。",
  reviewHint: "此发现需要先做出决定才能处理。",
  blockedHint: "此项目目前无法处理。请先完成下方步骤，再重新检查。",
  systemHint: "此项目需要先在 Wenlan 中处理，才能继续。",
  systemNext: {
    schema: "更新数据库后再重新检查。",
    searchIndex: "重建搜索索引后再重新检查。",
    update: "更新 Wenlan 后再重新检查。",
    restart: "重新启动 Wenlan 后再重新检查。",
    routeScope: "确认此链接使用的空间正确，再重新检查。",
    unknown: "打开详细信息查看需要处理的内容。",
  },
  nextStep: "下一步",
  orphanLinkNextStep: "创建缺少的笔记，或在原笔记中修正此链接。",
  statusDetails: "修复状态详细信息",
  errorDetails: "技术详细信息",
  page: "笔记",
  memory: "记忆",
  entity: "主题",
  other: "知识项目",
  memoryType: {
    identity: "身份",
    preference: "偏好",
    decision: "决定",
    lesson: "经验",
    gotcha: "注意事项",
    fact: "事实",
    unset: "未设置",
    unknown: "其他类型",
  },
  mutation: { reclassify: "记忆类型", bindLink: "笔记链接", linked: "已链接至其他笔记", notLinked: "「{{label}}」尚未链接", targetLoading: "正在加载链接笔记…", sourceLabel: "来源标签", emptySourceLabel: "来源标签为空", noSourceLabel: "没有来源标签", memoryRelationship: "记忆关系", selfReference: "指向自身", selfReferenceRemoved: "已移除自我引用", memoryTopicLink: "记忆与主题的链接", brokenMemoryTopicLink: "记忆与主题的链接已失效", brokenMemoryTopicLinkRemoved: "已移除失效链接；记忆与主题都会保留" },
};
