// SPDX-License-Identifier: AGPL-3.0-only
import {test,expect,type Page} from '@playwright/test';
import {installTauriMock,collectBrowserErrors} from './tauriMock';
import {createSpacesNavigationFixture} from './fixtures/spacesNavigation';
import {openWikiNote} from './helpers/wikiWorkspace';
import {resources} from '../src/i18n/resources';
const baseActivity={state:'blocked',last_activity_at:null,assets:[{kind:'memories',state:'blocked',done:0,total:7,blocked:7,steps:[{name:'store',state:'idle',done:7,total:7,failed:0,job:null},{name:'summarize',state:'blocked',done:0,total:7,failed:0,job:'everyday'}]}],everyday:{job:'everyday',lane:'none',model:null,mode:'unconfigured',available:false},synthesis:{job:'synthesis',lane:'none',model:null,mode:'unconfigured',available:false},refinement:{ready_for_review:1,not_ready:0,groups:[]}};
async function start(page:Page,{locale='en',theme='light',width=1440,mode='blocked',revision=false}:{locale?:'en'|'zh-Hant'|'zh-Hans',theme?:string,width?:number,mode?:string,revision?:boolean}={}){
 await page.setViewportSize({width,height:960});const errors=collectBrowserErrors(page);const base=createSpacesNavigationFixture();
 const pending={target_source_id:'page-architecture',target_kind:'page' as const,revision_source_id:'revision-time',revision_content:'# Fixture architecture\n\nMeet at 10:30 instead of 10:00.',source_agent:'Dev example',last_modified:1791468000};
 const fixture={...base,pendingRevisions:revision?[pending]:[],refinements:[{id:'cross-spaces',action:'cross_space_discovery' as const,source_ids:['memory-0','memory-1'],payload:{action:'cross_space_discovery' as const,spaces:['Travel','Reading'],memory_count:2},confidence:0.9,created_at:'2026-10-09 00:00:00'}],distillReview:{pages_created:0,scoped:false,created_ids:[],pending:[{source_ids:['memory-0','memory-1'],contents:['Fictional plan: meet at 10:30.','Bring the reading notes.'],space:'Travel',estimated_tokens:30}],stale_pages:[],stale_truncated:false,orphan_topics:[{label:'Weekend planning',count:2}]}};
 const runtime=await installTauriMock(page,{locale,rawActions:[],fixture,localStorage:{'wenlan-theme':theme}});
 const activity=structuredClone(baseActivity);if(mode==='running'){activity.state='organizing';activity.assets[0].state='running';activity.assets[0].steps[1].state='running';}else if(['off','waiting_for_idle','up_to_date','future'].includes(mode))activity.state=mode;
 await page.addInitScript(({activity,mode})=>{const orig=window.__wenlanTauriInvoke;let resolved=false;let failed=false;(window as any).__decisionWrites=[];window.__wenlanTauriInvoke=async(command,args)=>{
  if(command==='get_activity'){if(mode==='error'&&!failed){failed=true;throw new Error('activity unavailable');}return activity;}
  if(['accept_pending_revision','dismiss_pending_revision'].includes(command)){resolved=true;(window as any).__decisionWrites.push({command,args});return {wrote:true};}
  const result=await orig(command,args);if(command==='list_pending_revisions'&&resolved)return [];return result;
 };},{activity,mode});
 await page.goto('/');await page.evaluate(()=>document.fonts.ready);return {errors,runtime,tr:resources[locale].translation};
}
async function openActivity(page:Page){if(!(await page.getByTestId('activity-status').isVisible()))await page.locator('[data-sidebar-toggle=true]').click();await page.getByTestId('activity-status').click();await page.getByTestId('activity-summary-open').click();await expect(page.getByTestId('activity-now')).toBeVisible();}
function noMutation(calls:readonly {command:string}[]){expect(calls.filter(c=>['accept_refinement','reject_refinement','redistill_page','update_memory_cmd','create_page'].includes(c.command))).toEqual([]);}
test('review finishes after the real decision and keeps discoveries in Activity',async({page},info)=>{
 const {errors,runtime,tr}=await start(page,{revision:true});await openWikiNote(page,'Fixture architecture');await page.getByRole('button',{name:'Review changes',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(dialog.locator('ins')).not.toHaveCount(0);await page.screenshot({path:info.outputPath('real-decision.png')});await dialog.getByRole('button',{name:'Approve',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__decisionWrites.length)).toBe(1);await expect(dialog.getByRole('heading',{name:'Review complete',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Skip',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('review-complete.png')});await dialog.getByRole('button',{name:'Back to review',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText(tr.review.noDecisionsWaiting,{exact:true})).toBeVisible();await expect(page.getByText('EXAMPLE',{exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('decisions-complete.png')});await page.getByRole('button',{name:tr.review.openActivity,exact:true}).click();await expect(page.getByRole('heading',{name:tr.activityDiscoveries.title,exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:tr.activityDiscoveries.candidates,exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:tr.activityDiscoveries.proposals,exact:true})).toBeVisible();await expect(page.getByText(tr.activityDiscoveries.crossSpace,{exact:true})).toBeVisible();await expect(page.getByText('Travel',{exact:true})).toBeVisible();await expect(page.getByText(tr.activityDiscoveries.notGenerated,{exact:false})).toBeVisible();await page.screenshot({path:info.outputPath('retained-discoveries.png')});noMutation(runtime.calls());expect(errors.pageErrors).toEqual([]);expect(errors.consoleErrors).toEqual([]);
});
test('empty decision queue never fills itself with fake examples',async({page},info)=>{const {tr,errors}=await start(page);await openActivity(page);await page.getByRole('button',{name:tr.home.reviewPageChanges,exact:true}).click();await expect(page.getByText(tr.review.noDecisionsWaiting,{exact:true})).toBeVisible();await expect(page.getByText('EXAMPLE',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Skip',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('no-fake-decisions.png')});expect(errors.pageErrors).toEqual([]);});
for(const mode of ['running','off','waiting_for_idle','future'])test(`background state ${mode}`,async({page},info)=>{const {errors,runtime}=await start(page,{mode});await openActivity(page);await expect(page.getByTestId(`activity-now-${mode==='waiting_for_idle'?'waiting':mode==='future'?'unknown':mode}`)).toBeVisible();await page.screenshot({path:info.outputPath(`${mode}.png`)});noMutation(runtime.calls());expect(errors.pageErrors).toEqual([]);});
for(const locale of ['en','zh-Hant','zh-Hans'] as const)for(const theme of ['light','dark'])for(const width of [1440,375])test(`layout ${locale} ${theme} ${width}`,async({page},info)=>{
 test.skip(info.project.name!=='webkit');const {errors,runtime,tr}=await start(page,{locale,theme,width});await openActivity(page);await expect(page.getByRole('heading',{name:tr.activityStatus.nowTitle,exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:tr.activityDiscoveries.title,exact:true})).toBeVisible();await expect(page.getByTestId('activity-now-blocked')).toBeVisible();await expect(page.getByTestId('activity-now-idle')).toHaveCount(0);await expect(page.getByText(tr.activityStatus.processingDetails,{exact:true})).toHaveCount(0);await expect(page.getByText(tr.activityDiscoveries.crossSpace,{exact:true})).toBeVisible();await expect(page.getByText('Travel',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('activity-layout.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);expect(await page.locator('.mem-activity-discoveries').evaluate(e=>e.scrollWidth-e.clientWidth)).toBeLessThanOrEqual(1);noMutation(runtime.calls());expect(errors.pageErrors).toEqual([]);expect(errors.consoleErrors).toEqual([]);
});

for(const width of [1440,375])test(`default hierarchy and source reading ${width}`,async({page},info)=>{const {tr,errors,runtime}=await start(page,{locale:'zh-Hant',width,theme:width===1440?'light':'dark'});await openActivity(page);await expect(page.getByRole('heading',{name:tr.activityStatus.nowTitle,exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:tr.activityDiscoveries.title,exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:tr.activityDiscoveries.recent,exact:true})).toBeVisible();await expect(page.getByText('Travel',{exact:true})).toBeVisible();expect(runtime.calls().filter(c=>c.command==='distill_review').length).toBeGreaterThan(0);await page.screenshot({path:info.outputPath('activity-default.png')});await page.locator('.mem-activity-source-preview > summary').click();await expect(page.getByText('Fictional plan: meet at 10:30.',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('discovery-sources.png')});noMutation(runtime.calls());expect(errors.pageErrors).toEqual([]);});
