// SPDX-License-Identifier: AGPL-3.0-only
import {test,expect,type Page} from '@playwright/test';
import {installTauriMock,collectBrowserErrors} from './tauriMock';
import {openWikiNote} from './helpers/wikiWorkspace';
async function boot(page: Page){await page.setViewportSize({width:1440,height:900});const errors=collectBrowserErrors(page);const control=await installTauriMock(page,{locale:'en',rawActions:[]});await page.goto('/');await openWikiNote(page,'Fixture architecture');await page.getByRole('button',{name:'Open note sidebar',exact:true}).click();return {errors,control};}
test('unified Info has two tabs, graph and one canonical connection list',async({page},info)=>{
 const {errors}=await boot(page);await expect(page.locator('.note-inspector-tabs [role=tab]')).toHaveCount(2);await expect(page.getByRole('tab',{name:'Connections',exact:true})).toHaveCount(0);await expect(page.getByRole('group',{name:'Connections',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Open in graph',exact:true})).toBeVisible();await expect(page.locator('.knowledge-context-section')).toHaveCount(0);await expect(page.locator('.note-info-summary')).toBeVisible();await page.screenshot({path:info.outputPath('unified-info.png')});expect(errors.pageErrors).toEqual([]);
});
test('expanded presentation survives both tab directions, note switch and explicit restore',async({page},info)=>{
 const {errors,control}=await boot(page);await page.getByRole('tab',{name:'Mind map',exact:true}).click();await expect(page.locator('.page-canvas-surface')).toBeVisible();await page.getByRole('button',{name:'Expand workspace',exact:true}).click();const pane=page.locator('.page-info-drawer-expanded-workspace');await expect(pane).toBeVisible();await page.getByRole('tab',{name:'Info',exact:true}).click();await expect(pane).toBeVisible();await expect(page.locator('.page-detail-document')).toBeHidden();await expect(page.getByRole('group',{name:'Connections',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('expanded-info.png')});await openWikiNote(page,'Why fixtures stay deterministic');await expect(pane).toBeVisible();await expect(page.getByRole('tab',{name:'Info',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'Mind map',exact:true}).click();await expect(pane).toBeVisible();await expect(page.getByRole('region',{name:'Canvas for Why fixtures stay deterministic',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('expanded-map.png')});await page.getByRole('button',{name:'Return to sidebar',exact:true}).click();await expect(pane).toHaveCount(0);await expect(page.locator('.page-info-drawer-group-overlay-panel')).toBeVisible();await expect(page.locator('.page-detail-document')).toBeVisible();expect(control.calls().filter(c=>/^(update_page|create_page_map_node|patch_page_map_node|delete_page_map_node)$/.test(c.command))).toHaveLength(0);expect(errors.pageErrors).toEqual([]);
});
