import {test,expect,type Page} from '@playwright/test';
import {installTauriMock,collectBrowserErrors} from './tauriMock';
import {createSpacesNavigationFixture} from './fixtures/spacesNavigation';
import {openWikiNote} from './helpers/wikiWorkspace';
import {resources} from '../src/i18n/resources';
const group=(page:Page,id='primary')=>page.locator(`[data-note-group-id="${id}"]`);
const target='page-architecture';
async function start(page:Page,mode='pending',locale:'en'|'zh-Hant'|'zh-Hans'='en',width=1440,theme='light'){
 await page.setViewportSize({width,height:960});const errors=collectBrowserErrors(page);
 const base=createSpacesNavigationFixture();const pending={target_source_id:target,revision_source_id:'revision-current',revision_content:'# Fixture architecture\n\nA proposed replacement requiring confirmation.',target_kind:'page' as const,source_agent:'test-reviewer',last_modified:1789295400};
 const pagePending=['pending','dual','late','save-failure','partial-error'].includes(mode);
 const pendingRevisions=pagePending?[...(mode==='late'?Array.from({length:65},(_,i)=>({...pending,target_source_id:`unrelated-${i}`,revision_source_id:`rev-${i}`})):[]),pending]:mode==='cap'?Array.from({length:500},(_,i)=>({...pending,target_source_id:`unrelated-${i}`,revision_source_id:`rev-${i}`})):[];
 const fixture={...base,pages:base.pages.map(p=>({...p,review_status:'unconfirmed' as const,stale_reason:p.id===target&&['updated','conflict','blocked'].includes(mode)?(mode==='conflict'?'source_conflict':'source_updated'):undefined,refresh_blocked_reason:p.id===target&&mode==='blocked'?'citation_gate':undefined})),pendingRevisions,refinements:mode==='source'?[{id:'linked-conflict',action:'detect_contradiction' as const,source_ids:['memory-0','memory-1'],payload:{action:'detect_contradiction' as const},confidence:0.9,created_at:'2026-10-08 00:00:00'}]:[],distillReview:{pages_created:0,scoped:false,created_ids:[],pending:[],stale_pages:[],stale_truncated:false,orphan_topics:[]}};
 const runtime=await installTauriMock(page,{locale,rawActions:[],fixture,localStorage:{'wenlan-theme':theme},failures:mode==='partial-error'?[{command:'list_refinements',message:'offline',times:1}]:mode==='error'?[{command:'list_pending_revisions',message:'offline',times:1}]:[]});
 await page.addInitScript(()=>{const orig=window.__wenlanTauriInvoke;const resolved=new Set<string>();(window as any).__reviewWrites=[];window.__wenlanTauriInvoke=async(command,args)=>{
  if(command==='dismiss_pending_revision'||command==='accept_pending_revision'){const id=(args as any).sourceId;(window as any).__reviewWrites.push({command,id});resolved.add(id);return {target_source_id:id,revision_source_id:'revision-current',wrote:true};}
  const result=await orig(command,args);if(command==='list_pending_revisions'&&Array.isArray(result))return result.filter(v=>!resolved.has(v.target_source_id)).slice(0,(args as any)?.limit??50);return result;
 };});
 await page.goto('/');await openWikiNote(page,'Fixture architecture');await expect(group(page).locator('.cm-content[role=textbox]')).toBeVisible();await page.evaluate(()=>document.fonts.ready);return {runtime,errors,tr:resources[locale].translation};
}
test('baseline/current page shows a pending revision at its note',async({page},info)=>{await start(page);await expect(group(page).locator('.note-review-notice')).toContainText('1 item needs review');await page.screenshot({path:info.outputPath('pending-note.png')});});
test('opens exact page diff beyond the default queue limit, dismisses and clears on return',async({page},info)=>{
 const {runtime,errors}=await start(page,'late');await group(page).getByRole('button',{name:'Review changes',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(dialog.getByRole('heading',{name:'Fixture architecture',exact:true})).toBeVisible();await expect(dialog.locator('ins')).not.toHaveCount(0);await page.screenshot({path:info.outputPath('focused-diff.png')});
 expect(runtime.calls().filter(c=>c.command==='list_pending_revisions').some(c=>(c.args as any).limit===500)).toBe(true);await dialog.getByRole('button',{name:'Dismiss',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__reviewWrites.length)).toBe(1);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Back',exact:true}).click();await expect(group(page).getByRole('textbox',{name:'Page editor',exact:true})).toBeVisible();await expect(group(page).locator('.note-review-notice')).toHaveCount(0);expect(errors.pageErrors).toEqual([]);
});
test('two groups keep note ownership and secondary entry opens its exact item',async({page},info)=>{
 const {errors}=await start(page,'dual','en',1920,'dark');await openWikiNote(page,'Why fixtures stay deterministic');await group(page).getByRole('tab',{name:'Fixture architecture',exact:true}).click({button:'right'});await page.getByRole('menuitem',{name:'Move to right group',exact:true}).click();await expect(group(page).locator('.note-review-notice')).toHaveCount(0);await expect(group(page,'secondary').locator('.note-review-notice')).toContainText('1 item needs review');await page.screenshot({path:info.outputPath('two-groups.png')});await group(page,'secondary').getByRole('button',{name:'Review changes',exact:true}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:'Fixture architecture',exact:true})).toBeVisible();expect(errors.pageErrors).toEqual([]);
});
test('source contradiction routes to the existing two-source review',async({page},info)=>{await start(page,'source');await expect(group(page).locator('.note-review-notice')).toContainText('Related source issues (1)');await group(page).getByRole('button',{name:'Review changes',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Existing memory');await expect(page.getByRole('dialog')).toContainText('Newer memory');await page.screenshot({path:info.outputPath('source-conflict-dialog.png')});});
test('load failure is explicit and retry clears it without an all-clear badge',async({page},info)=>{await start(page,'error');const notice=group(page).locator('.note-review-notice');await expect(notice).toContainText('Could not check');await page.screenshot({path:info.outputPath('load-error.png')});await notice.getByRole('button',{name:'Retry',exact:true}).click();await expect(notice).toHaveCount(0);});
test('capped lists are incomplete and generic unconfirmed state stays quiet',async({page},info)=>{await start(page,'cap');await expect(group(page).locator('.note-review-notice')).toContainText('Only part');await page.screenshot({path:info.outputPath('incomplete.png')});await page.reload();});
test('successful local edit does not create a review notice',async({page})=>{const {runtime,errors}=await start(page,'clean');const editor=group(page).getByRole('textbox',{name:'Page editor',exact:true});await expect(group(page).locator('.note-review-notice')).toHaveCount(0);await editor.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.insertText('\nLocal addition');await expect.poll(()=>runtime.calls().filter(c=>c.command==='update_page').length).toBeGreaterThan(0);await expect(group(page).locator('.note-review-notice')).toHaveCount(0);expect(errors.pageErrors).toEqual([]);});
test('failed save blocks review navigation and retains the draft',async({page},info)=>{const {runtime}=await start(page,'save-failure');runtime.failNext('update_page','simulated unavailable',10);const editor=group(page).getByRole('textbox',{name:'Page editor',exact:true});await editor.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.insertText('\nPreserve this draft');await group(page).getByRole('button',{name:'Review changes',exact:true}).click();await expect(group(page).getByRole('textbox',{name:'Page editor',exact:true})).toContainText('Preserve this draft');await expect(page.getByRole('dialog')).toHaveCount(0);await expect.poll(()=>runtime.calls().filter(c=>c.command==='update_page').length).toBeGreaterThan(0);await page.screenshot({path:info.outputPath('save-blocked.png')});});
for(const mode of ['updated','conflict','blocked'])test(`inline ${mode} has an actionable details entry`,async({page},info)=>{await start(page,mode);const notice=group(page).locator('.note-review-notice');await expect(notice).toContainText(mode==='updated'?'A source changed':mode==='conflict'?'A source conflict':'The update could not finish');await expect(notice).not.toContainText('Updating');await notice.getByRole('button',{name:'View details',exact:true}).click();await expect(group(page).getByRole('tab',{name:'Info',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath(`${mode}.png`)});});
for(const locale of ['en','zh-Hant','zh-Hans'] as const)for(const theme of ['light','dark'])test(`layout ${locale} ${theme}`,async({page},info)=>{
 test.skip(info.project.name!=='webkit');const width=theme==='light'?1440:375;const {errors,tr}=await start(page,'pending',locale,width,theme);const n=group(page).locator('.note-review-notice');await expect(n).toContainText(tr.noteReview.pageRevision.replace('{{count}}','1'));await expect(n.getByRole('button',{name:tr.noteReview.reviewChanges,exact:true})).toBeInViewport();expect(await n.evaluate(e=>e.scrollWidth-e.clientWidth)).toBeLessThanOrEqual(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:info.outputPath('localized-note.png')});expect(errors.pageErrors).toEqual([]);expect(errors.consoleErrors).toEqual([]);
});
