#!/usr/bin/env bash
# weekly-review.sh - one command that holds up the mirror every week.
# Combines the self-dashboard (where your effort went) with the competitor radar
# (what moved in your lane) into a single markdown you actually read on Sunday.
# Run from repo root: bash overnight/automations/weekly-review/weekly-review.sh
#
# Pairs with a scheduled Claude Code web session (see SCHEDULED-PROMPT.md) that
# runs this, reads the output, and drafts a 5-line "what to do this week" plan.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"
DATE="$(date +%Y-%m-%d)"
DASH="overnight/tools/self-dashboard.sh"
RADAR="overnight/automations/competitor-radar/radar.sh"

echo "# Weekly review - ${DATE}"
echo
echo "## 1. Where your week actually went"
echo '```'
[ -f "$DASH" ] && bash "$DASH" 7 || echo "self-dashboard.sh not found at $DASH"
echo '```'
echo
echo "## 2. The lane this week (top rivals by stars)"
if [ -f "$RADAR" ]; then
  # radar prints a markdown table already; show the top 15 rows.
  bash "$RADAR" 2>/dev/null | head -20 || echo "_radar failed (network policy?). Run manually when online._"
else
  echo "_radar.sh not found at $RADAR_"
fi
echo
echo "## 3. The two questions to answer before you write any code this week"
echo "- Did a single real human touch the product or read my writing in the last 7 days? (If no, that is the week's job.)"
echo "- Is my inward ratio above 50% again? (If yes, I am hiding. Pick one outward task and ship it.)"
echo
echo "_Generated by weekly-review.sh. Edit the two questions as your situation changes._"
