// SPDX-License-Identifier: AGPL-3.0-only
export const enSourceAccess = {
  "addTitle": "Add a source",
  "files": "Add files",
  "filesHint": "PDF, Markdown or TXT",
  "folder": "Connect a folder",
  "folderHint": "Browse its files and keep supported documents up to date.",
  "web": "Add a web excerpt",
  "webHint": "Keep a URL together with text you copy from the page.",
  "close": "Close",
  "adding": "Adding…",
  "added": "Added",
  "addedBody": "{{name}} has been added. It will appear in the library after indexing.",
  "addFailed": "Could not add the source",
  "upgrade": "Your daemon needs an update to index files.",
  "update": "Update Wenlan",
  "webTitle": "Add a web excerpt",
  "url": "Web address",
  "urlPlaceholder": "https://",
  "title": "Title (optional)",
  "content": "Text from the page",
  "contentHint": "Paste the text you want to keep. Wenlan saves this excerpt; it does not fetch the website.",
  "urlInvalid": "Enter a complete http or https address.",
  "contentRequired": "Paste the text you want to keep.",
  "saveExcerpt": "Save excerpt",
  "replaceWarning": "This URL already has a saved excerpt. Replacing it will remove the earlier text. Your new text has not been saved yet.",
  "replaceExcerpt": "Replace existing excerpt",
  "excerptSaved": "Web excerpt saved",
  "cancel": "Cancel",
  "back": "Back to sources",
  "previewLoading": "Loading source…",
  "previewFailed": "Could not load this source.",
  "retry": "Try again",
  "noPreview": "No readable text is available for this source.",
  "webPreview": "This preview shows the available summary. Open the original page to read it in full.",
  "summary": "Summary",
  "openOriginal": "Open original",
  "openFailed": "Could not open the original.",
  "browse": "Choose folder…",
  "folderTitle": "Connect a folder",
  "folderBody": "Browse files from a folder on your computer. PDF, Markdown and TXT can be indexed; other files remain in the folder.",
  "folderPath": "Folder",
  "chooseFolder": "Choose a folder…",
  "scanning": "Checking folder…",
  "vaultDetected": "Obsidian vault detected",
  "connect": "Connect folder",
  "folderPickFailed": "Could not read the selected folder."
};

export const hantSourceAccess = {
  "addTitle": "加入來源",
  "files": "加入檔案",
  "filesHint": "PDF、Markdown 或 TXT",
  "folder": "連接資料夾",
  "folderHint": "瀏覽資料夾中的檔案，持續同步支援的文件。",
  "web": "加入網頁摘錄",
  "webHint": "把網址和從網頁複製的文字一起保存。",
  "close": "關閉",
  "adding": "加入中…",
  "added": "已加入",
  "addedBody": "已加入 {{name}}，建立索引後會出現在來源清單。",
  "addFailed": "無法加入來源",
  "upgrade": "需要更新背景服務才能建立檔案索引。",
  "update": "更新 Wenlan",
  "webTitle": "加入網頁摘錄",
  "url": "網頁網址",
  "urlPlaceholder": "https://",
  "title": "標題（選填）",
  "content": "網頁文字",
  "contentHint": "貼上想保留的文字。文瀾會保存這份摘錄，不會自動抓取網站。",
  "urlInvalid": "請輸入完整的 http 或 https 網址。",
  "contentRequired": "請貼上想保留的文字。",
  "saveExcerpt": "保存摘錄",
  "replaceWarning": "這個網址已有保存的摘錄。取代後會移除先前的文字；這次貼上的內容尚未保存。",
  "replaceExcerpt": "取代既有摘錄",
  "excerptSaved": "已保存網頁摘錄",
  "cancel": "取消",
  "back": "返回來源",
  "previewLoading": "正在載入來源…",
  "previewFailed": "無法載入這份來源。",
  "retry": "重試",
  "noPreview": "這份來源目前沒有可預覽的文字。",
  "webPreview": "此處顯示已有的摘要。完整內容可開啟原始網頁閱讀。",
  "summary": "摘要",
  "openOriginal": "開啟原始網頁",
  "openFailed": "無法開啟原始網頁。",
  "browse": "選擇資料夾…",
  "folderTitle": "連接資料夾",
  "folderBody": "瀏覽電腦上的資料夾。PDF、Markdown 和 TXT 可建立索引；其他檔案仍保留在原資料夾。",
  "folderPath": "資料夾",
  "chooseFolder": "選擇資料夾…",
  "scanning": "正在檢查資料夾…",
  "vaultDetected": "已偵測到 Obsidian 資料庫",
  "connect": "連接資料夾",
  "folderPickFailed": "無法讀取所選資料夾。"
};

export const hansSourceAccess = {
  "addTitle": "加入来源",
  "files": "加入文件",
  "filesHint": "PDF、Markdown 或 TXT",
  "folder": "连接文件夹",
  "folderHint": "浏览文件夹中的文件，持续同步支持的文档。",
  "web": "加入网页摘录",
  "webHint": "把网址和从网页复制的文字一起保存。",
  "close": "关闭",
  "adding": "加入中…",
  "added": "已加入",
  "addedBody": "已加入 {{name}}，建立索引后会出现在来源列表。",
  "addFailed": "无法加入来源",
  "upgrade": "需要更新后台服务才能建立文件索引。",
  "update": "更新 Wenlan",
  "webTitle": "加入网页摘录",
  "url": "网页网址",
  "urlPlaceholder": "https://",
  "title": "标题（选填）",
  "content": "网页文字",
  "contentHint": "粘贴想保留的文字。文澜会保存这份摘录，不会自动抓取网站。",
  "urlInvalid": "请输入完整的 http 或 https 网址。",
  "contentRequired": "请粘贴想保留的文字。",
  "saveExcerpt": "保存摘录",
  "replaceWarning": "这个网址已有保存的摘录。替换后会移除先前的文字；这次粘贴的内容尚未保存。",
  "replaceExcerpt": "替换已有摘录",
  "excerptSaved": "已保存网页摘录",
  "cancel": "取消",
  "back": "返回来源",
  "previewLoading": "正在加载来源…",
  "previewFailed": "无法加载这份来源。",
  "retry": "重试",
  "noPreview": "这份来源目前没有可预览的文字。",
  "webPreview": "此处显示已有的摘要。完整内容可打开原始网页阅读。",
  "summary": "摘要",
  "openOriginal": "打开原始网页",
  "openFailed": "无法打开原始网页。",
  "browse": "选择文件夹…",
  "folderTitle": "连接文件夹",
  "folderBody": "浏览电脑上的文件夹。PDF、Markdown 和 TXT 可建立索引；其他文件仍保留在原文件夹。",
  "folderPath": "文件夹",
  "chooseFolder": "选择文件夹…",
  "scanning": "正在检查文件夹…",
  "vaultDetected": "已检测到 Obsidian 库",
  "connect": "连接文件夹",
  "folderPickFailed": "无法读取所选文件夹。"
};
