// SPDX-License-Identifier: AGPL-3.0-only
//
// Locale literals for the FirstUseGuide sample walkthrough. Imported by
// src/i18n/resources.ts into the `firstUse` namespace of every locale.
// The three objects must keep identical key sets (parity is enforced by
// src/i18n/resources.test.ts). Tutorial walkthrough content itself lives in
// firstUseSampleData.ts, with a matching dataset for each supported locale.

export const enFirstUse = {
  entry: "Take a quick tour",
  guide: {
    eyebrow: "First-use guide",
    title: "Turn scattered notes into knowledge you can reuse.",
    lede: "See how memories, files, and existing pages become one cited page your AI tools can use — then bring your own data.",
    tryExample: "Try an example",
    bringData: "Bring my data",
    seeKnowledge: "See my knowledge",
    step1Title: "Bring data in",
    step1Body:
      "Paste memories, import files, or connect an AI tool to get started.",
    step2Title: "Wenlan organizes it",
    step2Body:
      "Decisions are pulled out, linked, and compiled into pages — every claim keeps its source.",
    step3Title: "Your AI reuses it",
    step3Body:
      "Ask from any connected tool and get answers with sources you can open.",
    back: "Back",
  },
  chooser: {
    title: "Bring your own data",
    body: "Start with notes you already have, or connect the AI tool you use.",
    pasteTitle: "Paste memories",
    pasteBody: "One memory per line, from a chat export or your own notes.",
    pasteAction: "Open import",
    filesTitle: "Import files or a folder",
    filesBody: "Point Wenlan at notes, docs, or a whole directory.",
    filesAction: "Open sources",
    connectTitle: "Connect an AI tool",
    connectBody: "Let your assistant write to Wenlan as it works.",
    connectAction: "Set up a tool",
    back: "Back",
  },
  sample: {
    animationLabel: "Sample walkthrough · not live processing",
    phaseImport: "Bring sources in",
    phaseImportBody: "Three kinds of raw material enter the workspace.",
    phaseExtract: "Pull out what matters",
    phaseExtractBody: "The usable decisions are lifted out of each source.",
    phaseConnect: "Link back to sources",
    phaseConnectBody: "Every point keeps a path back to where it came from.",
    phaseForm: "Form the knowledge page",
    phaseFormBody: "The points are arranged into one page you can keep using.",
    pause: "Pause",
    play: "Play",
    next: "Next step",
    replay: "Replay",
    skipToResult: "Skip to result",
    back: "Back to guide",
    sourcesTitle: "Sources",
    citationTitle: "Original source",
    fileOrigin: "File {{path}} · line {{line}}",
    memoryOrigin: "Captured from conversation",
    pageOrigin: "Existing knowledge page",
    close: "Close",
    relatedTitle: "Related",
    openRelated: "Open related page",
    backToPage: "Back to the page",
    pageEyebrow: "Sample knowledge page · 3 sources",
    useTitle: "Let AI use your knowledge",
    useBody:
      "Pick a tool below. Copy a command, then paste it into a new conversation to work with your own imported data.",
    clientChatgpt: "ChatGPT",
    clientCodex: "Codex",
    clientClaude: "Claude",
    recallLabel: "Recall from a new conversation:",
    handoffLabel: "Leave progress behind",
    handoffHint: "Run it when work ends, so the next session can continue.",
    briefLabel: "Brief a new conversation",
    briefHint: "Run it at the start of a NEW conversation to pick up earlier work.",
    copyCommand: "Copy command",
    copied: "Copied",
    copyFailed: "Copy failed — select the text and copy it manually.",
    notInLibrary:
      "Sample only — not in your library, and your AI cannot retrieve it.",
    connectCta: "Connect my AI",
    bringCta: "Bring my data",
    useWithAi: "Use with AI",
    formingNote: "The page will take shape here as the sources are organized.",
    pointsTitle: "Key points so far",
    connectHint: "Connect one of your tools first — then paste a command into a brand-new conversation.",
  },
  live: {
    title: "Your knowledge, live",
    body: "Follow your imports and open the knowledge Wenlan has organized.",
    waiting: "Reading your library…",
    loadFailed: "Wenlan couldn't read this right now.",
    retry: "Retry",
    refresh: "Refresh",
    emptyTitle: "Nothing here yet",
    emptyBody: "Import memories or connect a source, and progress will show up here.",
    importAction: "Import memories",
    intelligenceAction: "Set up intelligence",
    queuedNote: "Your memories are saved and ready to use. Wenlan will show organization progress as it works.",
    needsIntelligence: "Your data is saved. Set up an available AI model to continue organizing it into pages.",
    activeTitle: "Import progress",
    settledNoPages:
      "No knowledge page was created in this batch. Check your model setup or add more related material.",
    failedNote: "Some items could not be processed. Check the failed stages above and your model settings.",
    yourPages: "Your knowledge pages",
    yourPagesNote: "From your library today — not necessarily from the import above.",
    noActiveImports: "No active imports. New imports will report their progress here.",
    back: "Back to guide",
  },
};

export const hansFirstUse = {
  entry: "快速导览",
  guide: {
    eyebrow: "新手导览",
    title: "把零散的记录，变成用得上的知识。",
    lede: "看看记忆、文件和已有页面如何变成一页 AI 可用的、带出处的知识——然后带入你自己的数据。",
    tryExample: "试用示例",
    bringData: "带入我的数据",
    seeKnowledge: "查看我的知识",
    step1Title: "带入数据",
    step1Body: "粘贴记忆、导入文件，或连接一个 AI 工具，开始第一步。",
    step2Title: "文澜负责整理",
    step2Body: "提取决定、建立关联、汇编成页面——每条结论都保留出处。",
    step3Title: "AI 随时复用",
    step3Body: "在任何已连接的工具中提问，得到附带可打开出处来源的回答。",
    back: "返回",
  },
  chooser: {
    title: "带入你自己的数据",
    body: "从已有的笔记开始，或连接你常用的 AI 工具。",
    pasteTitle: "粘贴记忆",
    pasteBody: "每行一条记忆，来自对话导出或你自己的笔记。",
    pasteAction: "打开导入",
    filesTitle: "导入文件或文件夹",
    filesBody: "把笔记、文档或整个目录交给文澜。",
    filesAction: "打开来源",
    connectTitle: "连接 AI 工具",
    connectBody: "让你的助手在工作时写入文澜。",
    connectAction: "设置工具",
    back: "返回",
  },
  sample: {
    animationLabel: "示例演示 · 非实时处理",
    phaseImport: "带入来源",
    phaseImportBody: "三种原始材料进入工作区。",
    phaseExtract: "提取关键内容",
    phaseExtractBody: "把用得上的决定从每份来源中提炼出来。",
    phaseConnect: "连回出处",
    phaseConnectBody: "每个要点都保留一条回到出处的路。",
    phaseForm: "形成知识页",
    phaseFormBody: "把要点排成一页可以继续使用的知识。",
    pause: "暂停",
    play: "播放",
    next: "下一步",
    replay: "重播",
    skipToResult: "跳到结果",
    back: "回到导览",
    sourcesTitle: "来源",
    citationTitle: "原始出处",
    fileOrigin: "文件 {{path}} · 第 {{line}} 行",
    memoryOrigin: "来自对话记录",
    pageOrigin: "已有知识页面",
    close: "关闭",
    relatedTitle: "相关",
    openRelated: "打开相关页面",
    backToPage: "回到本页",
    pageEyebrow: "示例知识页 · 3 个来源",
    useTitle: "让 AI 用上你的知识",
    useBody: "在下面选一个工具。复制指令，然后粘贴到新对话中，处理你自己导入的数据。",
    clientChatgpt: "ChatGPT",
    clientCodex: "Codex",
    clientClaude: "Claude",
    recallLabel: "在新对话中回忆：",
    handoffLabel: "留下工作进度",
    handoffHint: "工作结束时运行，让下一次会话可以接续。",
    briefLabel: "为新对话做简报",
    briefHint: "在新对话开始时运行，接上之前的工作。",
    copyCommand: "复制指令",
    copied: "已复制",
    copyFailed: "复制失败——请手动选择文本复制。",
    notInLibrary: "仅为示例——不在你的知识库中，你的 AI 也检索不到它。",
    connectCta: "连接我的 AI",
    bringCta: "带入我的数据",
    useWithAi: "让 AI 使用",
    formingNote: "来源整理完成后，页面会在这里成形。",
    pointsTitle: "目前的重点",
    connectHint: "先连接一个工具——再把指令粘贴到全新的对话中。",
  },
  live: {
    title: "你的知识 · 实时",
    body: "看看资料整理到哪一步，再打开文澜整理好的知识。",
    waiting: "正在读取你的知识库…",
    loadFailed: "文澜暂时无法读取。",
    retry: "重试",
    refresh: "刷新",
    emptyTitle: "这里还没有内容",
    emptyBody: "导入记忆或连接来源后，进度会出现在这里。",
    importAction: "导入记忆",
    intelligenceAction: "设置智能",
    queuedNote: "记忆已保存，可先使用。文澜会显示后续的整理进度。",
    needsIntelligence: "资料已保存。请设置可用的 AI 模型，才能继续整理成页面。",
    activeTitle: "导入进度",
    settledNoPages: "这次导入还没有产生知识页面。可以检查模型设置，或补充相关资料。",
    failedNote: "部分资料整理失败。请查看上方阶段状态，并检查模型设置。",
    yourPages: "你的知识页面",
    yourPagesNote: "来自你今天的知识库——不一定来自上面的导入。",
    noActiveImports: "暂无进行中的导入。新的导入会在这里报告进度。",
    back: "回到导览",
  },
};

export const hantFirstUse = {
  entry: "快速導覽",
  guide: {
    eyebrow: "新手導覽",
    title: "把零散的記錄，變成用得上的知識。",
    lede: "看看記憶、檔案和已有頁面如何變成一頁 AI 可用的、帶出處的知識——然後帶入你自己的資料。",
    tryExample: "試用範例",
    bringData: "帶入我的資料",
    seeKnowledge: "查看我的知識",
    step1Title: "帶入資料",
    step1Body: "貼上記憶、匯入檔案，或連接一個 AI 工具，開始第一步。",
    step2Title: "文瀾負責整理",
    step2Body: "提取決定、建立關聯、彙編成頁面——每條結論都保留出處。",
    step3Title: "AI 隨時重用",
    step3Body: "在任何已連接的工具中提問，得到附帶可開啟出處來源的回答。",
    back: "返回",
  },
  chooser: {
    title: "帶入你自己的資料",
    body: "從已有的筆記開始，或連接你常用的 AI 工具。",
    pasteTitle: "貼上記憶",
    pasteBody: "每行一則記憶，來自對話匯出或你自己的筆記。",
    pasteAction: "開啟匯入",
    filesTitle: "匯入檔案或資料夾",
    filesBody: "把筆記、文件或整個目錄交給文瀾。",
    filesAction: "開啟來源",
    connectTitle: "連接 AI 工具",
    connectBody: "讓你的助手在工作時寫入文瀾。",
    connectAction: "設定工具",
    back: "返回",
  },
  sample: {
    animationLabel: "範例演示 · 非即時處理",
    phaseImport: "帶入來源",
    phaseImportBody: "三種原始材料進入工作區。",
    phaseExtract: "提取關鍵內容",
    phaseExtractBody: "把用得上的決定從每份來源中提煉出來。",
    phaseConnect: "連回出處",
    phaseConnectBody: "每個要點都保留一條回到出處的路。",
    phaseForm: "形成知識頁",
    phaseFormBody: "把要點排成一頁可以繼續使用的知識。",
    pause: "暫停",
    play: "播放",
    next: "下一步",
    replay: "重播",
    skipToResult: "跳到結果",
    back: "回到導覽",
    sourcesTitle: "來源",
    citationTitle: "原始出處",
    fileOrigin: "檔案 {{path}} · 第 {{line}} 行",
    memoryOrigin: "來自對話記錄",
    pageOrigin: "已有知識頁面",
    close: "關閉",
    relatedTitle: "相關",
    openRelated: "開啟相關頁面",
    backToPage: "回到本頁",
    pageEyebrow: "範例知識頁 · 3 個來源",
    useTitle: "讓 AI 用上你的知識",
    useBody: "在下面選一個工具。複製指令，然後貼到新對話中，處理你自己匯入的資料。",
    clientChatgpt: "ChatGPT",
    clientCodex: "Codex",
    clientClaude: "Claude",
    recallLabel: "在新對話中回憶：",
    handoffLabel: "留下工作進度",
    handoffHint: "工作結束時執行，讓下一次會話可以接續。",
    briefLabel: "為新對話做簡報",
    briefHint: "在新對話開始時執行，接上之前的工作。",
    copyCommand: "複製指令",
    copied: "已複製",
    copyFailed: "複製失敗——請手動選取文字複製。",
    notInLibrary: "僅為範例——不在你的知識庫中，你的 AI 也擷取不到它。",
    connectCta: "連接我的 AI",
    bringCta: "帶入我的資料",
    useWithAi: "讓 AI 使用",
    formingNote: "來源整理完成後，頁面會在這裡成形。",
    pointsTitle: "目前的重點",
    connectHint: "先連接一個工具——再把指令貼到全新的對話中。",
  },
  live: {
    title: "你的知識 · 即時",
    body: "看看資料整理到哪一步，再打開文瀾整理好的知識。",
    waiting: "正在讀取你的知識庫…",
    loadFailed: "文瀾暫時無法讀取。",
    retry: "重試",
    refresh: "重新整理",
    emptyTitle: "這裡還沒有內容",
    emptyBody: "匯入記憶或連接來源後，進度會出現在這裡。",
    importAction: "匯入記憶",
    intelligenceAction: "設定智慧",
    queuedNote: "記憶已保存，可先使用。文瀾會顯示後續的整理進度。",
    needsIntelligence: "資料已保存。請設定可用的 AI 模型，才能繼續整理成頁面。",
    activeTitle: "匯入進度",
    settledNoPages: "這次匯入還沒有產生知識頁。可以檢查模型設定，或補充相關資料。",
    failedNote: "部分資料整理失敗。請查看上方階段狀態，並檢查模型設定。",
    yourPages: "你的知識頁面",
    yourPagesNote: "來自你今天的知識庫——不一定來自上面的匯入。",
    noActiveImports: "暫無進行中的匯入。新的匯入會在這裡報告進度。",
    back: "回到導覽",
  },
};
